package org.reactome.nursa.fireworks.client;

import org.reactome.web.fireworks.client.FireworksViewerImpl;
import org.reactome.web.nursa.analysis.client.model.PseudoResourceSummary;

public class NursaFireworksViewer extends FireworksViewerImpl {

    public NursaFireworksViewer(String json) {
        super(json);
    }

    @Override
    protected void filterResultBySpecies(String token, String resource) {
        // This is a no-op for results not generated by the standard
        // Reactome analysis server.
        if (!PseudoResourceSummary.RESOURCE.equals(resource)) {
            super.filterResultBySpecies(token, resource);
        }
    }

}
